---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-exp
parameters:
  fsType: ext4
  type: gp3
#  encrypted: "true"
#  kmsKeyId: <your-kms-key-arn>
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete # deletes the volume if PVC is removed
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: prabhjotbawa/testapp:0.0.1
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: gp3-exp
        resources:
          requests:
            storage: 5Gi